version: '2'

services:
  notebook-dev:
    build:
      context:  ./
    volumes:
      - ${HOME}:${HOME}
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    env_file:
      - env.list
    ports:
      - "8888:8888"
